### ISSUE TITLE
add elseif or elif  

### ISSUE THREAD

**Issue by joshkamau** [yogthos/Selmer#109]
If possible, i would really appreciate if elseif or elif would be added.

**Comment by yogthos** [comment]
Unfortunately, that would be a bit of a redesign in how the tags are parsed. I probably wouldn't have time to look at this in the near future.

**Comment by joshkamau** [comment]
No problem. Thanks.

**Comment by lensgolda** [comment]
> If possible, i would really appreciate if elseif or elif would be added.

Fully support this request. Very uncomfortable to work without `{ % elseif/elif %} `tags.

**Comment by rutchkiwi** [comment]
Since this is quite an issue in my project, I was gonna give this a go - but man if became tricky fast! I guess it requires quite a large re-do of how the tags are parsed and read as you said @yogthos, since currently the tags are parsed into a map, which does not allow for multiple occurances of a single "end-tag" like `elif`. Since this would need a re-do of the internal "tag representation", it would then require a change in how all the tags are processed later as well?

Worse, I guess perhaps this change would break existing custom tags - as the map they currently received would change its structure?

Did you ever think anything about how you'd want to do this @yogthos? Perhaps an easy but not very elegant solution would be to do something like `elif1, elif2 elif3 etc.?`? Or divide tags into two types, normal ones and a new, duplicate-end-tags-allowed type?

**Comment by yogthos** [comment]
Yeah, unfortunately this would require a bit of a redesign. I'd be ok with a breaking change for the custom tags in this case, but would definitely be a bit of work to do this properly.

One possibility might be to allow using a vector as the key to denote repeating tags, e.g: `[:elif]` could be used to denote a repeating tag, and then the parser could tag them as `:elif1`, `:elif2`, and so on as it reads them to make them distinct.

It's been a little while since I've looked at this, but [here](https://github.com/yogthos/Selmer/blob/0dfa6a2826fccafaefd8d6d3b846785c64945fd8/src/selmer/parser.clj#L204) would be the place to start if you do decide to dive into it. :)

**Comment by rutchkiwi** [comment]
Thanks! Sounds clever witht the elif1,2 as you described it. I will try to do something but don't hold your breath. :)

**Comment by yogthos** [comment]
Sounds like a plan, and yeah no pressure. :)
